# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: member.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'member.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cmember.proto\x12\x06member\"+\n\x0cStoreRequest\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\"\x18\n\nStoreReply\x12\n\n\x02ok\x18\x01 \x01(\x08\"\x18\n\nGetRequest\x12\n\n\x02id\x18\x01 \x01(\t\"*\n\x08GetReply\x12\r\n\x05\x66ound\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2o\n\rMemberService\x12\x31\n\x05Store\x12\x14.member.StoreRequest\x1a\x12.member.StoreReply\x12+\n\x03Get\x12\x12.member.GetRequest\x1a\x10.member.GetReplyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'member_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_STOREREQUEST']._serialized_start=24
  _globals['_STOREREQUEST']._serialized_end=67
  _globals['_STOREREPLY']._serialized_start=69
  _globals['_STOREREPLY']._serialized_end=93
  _globals['_GETREQUEST']._serialized_start=95
  _globals['_GETREQUEST']._serialized_end=119
  _globals['_GETREPLY']._serialized_start=121
  _globals['_GETREPLY']._serialized_end=163
  _globals['_MEMBERSERVICE']._serialized_start=165
  _globals['_MEMBERSERVICE']._serialized_end=276
# @@protoc_insertion_point(module_scope)
